SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN TRAN;
UPDATE Client SET nume='Jen' WHERE prenume='Ion';
WAITFOR DELAY '00:00:05';
UPDATE Producator SET licenta='lic9999999' WHERE nume='Sun Pharma';


COMMIT TRAN;