//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atletism_GUI.NET.repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Copil
    {
        public long Id { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public long Varsta { get; set; }
    }
}
