//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atletism_GUI.NET.config
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proba
    {
        public long Id { get; set; }
        public long CopilID { get; set; }
        public long Distanta { get; set; }
    }
}
